apiVersion: v1
kind: Namespace
metadata:
  name: openshift-osd-metrics
  annotations:
    package-operator.run/phase: namespace
    package-operator.run/collision-protection: IfNoController
  labels:
    openshift.io/cluster-monitoring: "true"
