kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter
  namespace: openshift-config
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
