apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
  name: prometheus-k8s
  namespace: openshift-osd-metrics
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
